name: Playwright Tests

on:
  push:
    branches:
      - master
      - feature/**
  pull_request:
    branches:
      - master

jobs:
  ui-tests:
    name: UI Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run UI tests
        run: npx playwright test tests/ui
        env:
          UI_BASE_URL: https://www.saucedemo.com
          API_BASE_URL: https://restful-booker.herokuapp.com

      - name: Upload UI Monocart Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: monocart-ui-report
          path: monocart-report/

  api-tests:
    name: API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run API tests
        run: npx playwright test tests/api
        env:
          UI_BASE_URL: https://www.saucedemo.com
          API_BASE_URL: https://restful-booker.herokuapp.com

      - name: Upload API Monocart Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: monocart-api-report
          path: monocart-report/