name: Playwright Test Suite (UI + API)

on:
  push:
    branches:
      - master
      - main
      - feature/**
  pull_request:
    branches:
      - master
      - main

jobs:

  ui-tests:
    name: UI Tests (@ui)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: npx playwright install --with-deps

      - name: Run UI tests
        run: npx playwright test --grep "@ui"
        env:
          UI_BASE_URL: https://www.saucedemo.com
          API_BASE_URL: https://restful-booker.herokuapp.com

      - name: Upload UI Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: monocart-ui-report
          path: monocart-report/

  api-tests:
    name: API Tests (@api)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: npx playwright install --with-deps

      - name: Run API tests
        run: npx playwright test --grep "@api"
        env:
          API_BASE_URL: https://restful-booker.herokuapp.com

      - name: Upload API Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: monocart-api-report
          path: monocart-report/